[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 300 --worker-class sync --keep-alive 80 --config gunicorn.conf.py app:app"
healthcheckPath = "/health"
healthcheckTimeout = 300
